import assert from 'node:assert/strict';
import {fixture} from './edit_harness.mjs';
const path=process.argv[2];
const f=fixture(path,'Heading.plain sentence',false);
const r=await f.sandbox.api.opReplace({find:'plain sentence',replace:'new sentence',expected_matches:1});
assert.equal(r.matches[0].fontBefore.bold,false);assert.equal(r.matches[0].fontAfter.bold,false);
assert.equal(f.state.chars[8].bold,false);
const mixed=fixture(path,'Heading.plain sentence',false);
await assert.rejects(()=>mixed.sandbox.api.opReplace({find:'Heading.plain',replace:'new',expected_matches:1}),e=>e.code==='MIXED_FORMATTING');
assert.equal(mixed.state.text,'Heading.plain sentence');
const previous=fixture(path,'Heading.plain sentence',false);
const p=await previous.sandbox.api.opReplace({find:'plain sentence',replace:'new',expected_matches:1,inherit_format:'previous'});
assert.equal(p.matches[0].fontAfter.bold,true);
const none=fixture(path,'Heading.plain sentence',false);
const n=await none.sandbox.api.opReplace({find:'Heading.',replace:'new',expected_matches:1,inherit_format:'none'});
assert.equal(n.matches[0].fontAfter.bold,false);
const fmt=fixture(path,'plain sentence',false);
const formatted=await fmt.sandbox.api.opFormat({find:'sentence',expected_matches:1,bold:true,italic:true,underline:true});
assert.equal(formatted.matches[0].boldAfter,true);assert.equal(formatted.matches[0].italicAfter,true);assert.equal(formatted.matches[0].underlineAfter,true);
console.log('formatting behavior passed');
