import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import assert from 'node:assert/strict';
import {DOMParser,EMPTY} from './shape_dom.mjs';
import {fixture} from './edit_harness.mjs';
const w='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const wp='http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing';
const shape='<wp:anchor><wp:positionH relativeFrom="page"><wp:posOffset>25</wp:posOffset></wp:positionH><wp:extent cx="100" cy="200"/><wp:docPr id="7" name="Sidebar"/></wp:anchor>';
const xml=`<w:document xmlns:w="${w}" xmlns:wp="${wp}"><w:body><w:p><w:r><w:t>Anchor</w:t>${shape}</w:r></w:p></w:body></w:document>`;
let current=xml, wrote=0;
const ctx={document:{body:{getOoxml:()=>({value:current})}},sync:async()=>{}};
const sandbox={DOMParser,console,crypto:webcrypto,TextEncoder,Word:{run:fn=>fn(ctx)},Office:{onReady(){}},
 document:{getElementById:()=>({addEventListener(){}})}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(process.argv[2],'utf8')+'\nglobalThis.api={inventoryShapes,guardAnchoredBodies,guardAnchoredParagraphs,dispatchOp};',sandbox);
const api=sandbox.api;
let inv=api.inventoryShapes(xml);
assert.equal(inv.length,1);assert.equal(inv[0].anchor_paragraph.text,'Anchor');
assert.equal(inv[0].anchor_paragraph.index,1);assert.equal(inv[0].size_emu.width,'100');
assert.equal(inv[0].horizontal_position.value,'25');
assert.equal(api.inventoryShapes(EMPTY).length,0);
await assert.rejects(()=>api.guardAnchoredBodies(ctx,[{getOoxml:()=>({value:xml})}]),e=>e.code==='ANCHORED_SHAPES');
await assert.rejects(()=>api.guardAnchoredParagraphs(ctx,[{paragraphs:{load(){},items:[{getOoxml:()=>({value:xml})}]}}]),e=>e.code==='ANCHORED_SHAPES');
await api.guardAnchoredBodies(ctx,[{getOoxml:()=>({value:EMPTY})}]);
vm.runInContext('dispatchOpUnchecked = async () => { globalThis.wrote(); return {applied:true}; };',sandbox);
sandbox.wrote=()=>{wrote++;};
const result=await api.dispatchOp('format',{});
assert.equal(result.shapes_before,1);assert.equal(result.shapes_after,1);
await assert.rejects(()=>api.dispatchOp('revisions_accept',{}),e=>e.code==='ANCHORED_SHAPES');
assert.equal(wrote,1);
sandbox.wrote=()=>{current=EMPTY;};
await assert.rejects(()=>api.dispatchOp('format',{}),e=>e.code==='VERIFICATION_FAILED');
const legacy=`<w:document xmlns:w="${w}" xmlns:v="urn:schemas-microsoft-com:vml"><w:body><w:p><v:shape id="v1" style="width:40pt;height:50pt"/></w:p></w:body></w:document>`;
assert.equal(api.inventoryShapes(legacy)[0].legacy_style,'width:40pt;height:50pt');
await assert.rejects(()=>api.guardAnchoredBodies(ctx,[{getOoxml:()=>({value:'<broken'})}]),e=>e.code==='HOST_SHAPE_READ_FAILED');
const edit=fixture(process.argv[2],'plain sentence',false);
edit.state.paragraphXml=xml;
await assert.rejects(()=>edit.sandbox.api.opReplace({find:'plain',replace:'new',expected_matches:1}),e=>e.code==='ANCHORED_SHAPES');
assert.equal(edit.state.text,'plain sentence');assert.equal(edit.state.queue.length,0);
console.log('shape inventory and guard passed');
