"""Unit tests for src/verified_docx_mcp/server.py.

Covers the two issue #28 WP-02 acceptance items not already covered by
test_render.py / test_paths.py:

  - error mapping: execute_export_pdf() translates render.RenderError codes
    1:1 onto this server's own ErrorCode/VerifyError envelope (exercised,
    like test_render.py's ErrorMappingTests, via a fake `osascript` earlier
    on PATH rather than a real Word instance).
  - owner-file parsing: Word's "~$*" suffix-matching rule and LibreOffice's
    ".~lock.<name>#", both via synthetic fixtures (see paths.py / server.py
    docstrings for why real-Word-generated bytes are out of reach here —
    a LEAD: acceptance item).
"""

from __future__ import annotations

import os
import stat
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))

from verified_docx_mcp import paths, server
from verified_docx_mcp.errors import ErrorCode, VerifyError


def _write_fake_osascript(bin_dir: Path, stderr_text: str, exit_code: int = 1) -> None:
    script = bin_dir / "osascript"
    script.write_text(
        "#!/bin/sh\n"
        f"echo {stderr_text!r} 1>&2\n"
        f"exit {exit_code}\n",
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


class ExportPdfErrorMappingTests(unittest.TestCase):
    """execute_export_pdf()'s RenderError -> VerifyError translation.

    Guarded on Word's sandbox container directory actually existing —
    render_word() checks that BEFORE ever invoking osascript (same guard
    as test_render.py's ErrorMappingTests)."""

    def setUp(self):
        import verified_docx_mcp.render as render_module

        if not render_module._word_sandbox_root().is_dir():
            self.skipTest(
                "Word's sandbox container directory does not exist on this "
                "machine (Word never launched)."
            )
        self._tmp = tempfile.TemporaryDirectory()
        self._bin_dir = Path(self._tmp.name) / "bin"
        self._bin_dir.mkdir()
        self._old_path = os.environ.get("PATH", "")
        os.environ["PATH"] = f"{self._bin_dir}{os.pathsep}{self._old_path}"

        self._old_allowed = os.environ.get(paths._ALLOWED_FILE_ROOTS_ENV)
        os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._tmp.name

        self._in_path = Path(self._tmp.name) / "test-input.docx"
        self._in_path.write_bytes(b"not a real docx, but osascript never reads it")
        self._out_path = Path(self._tmp.name) / "out" / "test-output.pdf"
        self._out_path.parent.mkdir()

    def tearDown(self):
        os.environ["PATH"] = self._old_path
        if self._old_allowed is None:
            os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        else:
            os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._old_allowed
        self._tmp.cleanup()

    def test_automation_not_granted_maps_through(self):
        _write_fake_osascript(
            self._bin_dir,
            "execution error: Not authorized to send Apple events to Microsoft Word. (-1743)",
        )
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), str(self._out_path))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.AUTOMATION_NOT_GRANTED)

    def test_other_failure_maps_to_render_failed(self):
        _write_fake_osascript(self._bin_dir, "Error: Message not understood.")
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), str(self._out_path))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.RENDER_FAILED)
        self.assertIn("Message not understood", str(ctx.exception.envelope.diagnostics))


class ExportPdfPathValidationTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self._old_allowed = os.environ.get(paths._ALLOWED_FILE_ROOTS_ENV)
        os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._tmp.name
        self._in_path = Path(self._tmp.name) / "in.docx"
        self._in_path.write_bytes(b"stub")

    def tearDown(self):
        if self._old_allowed is None:
            os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        else:
            os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._old_allowed
        self._tmp.cleanup()

    def test_missing_parent_directory_rejected(self):
        out = Path(self._tmp.name) / "does-not-exist-dir" / "out.pdf"
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), str(out))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.INVALID_INPUT)

    def test_empty_output_path_rejected(self):
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), "")
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.INVALID_INPUT)

    def test_missing_source_rejected(self):
        out = Path(self._tmp.name) / "out.pdf"
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(Path(self._tmp.name) / "nope.docx"), str(out))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.INVALID_INPUT)

    def test_output_path_under_scratch_root_accepted(self):
        # issue #101: with VERIFIED_DOCX_MCP_ALLOWED_FILE_ROOTS unset, an
        # output_path under the (patched) Claude Code scratch root resolves
        # rather than being rejected as outside the allowed roots.
        os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        with tempfile.TemporaryDirectory() as scratch_dir:
            scratch_root = Path(scratch_dir)
            out = scratch_root / "out.pdf"
            with mock.patch.object(paths, "_claude_code_scratch_root", return_value=scratch_root):
                resolved = server._resolve_export_output_path(str(out))
            self.assertEqual(resolved, out.resolve())


class WordOwnerFileMatchTests(unittest.TestCase):
    """core/document-backend-protocol.md §9's shared-filename-suffix rule."""

    def test_short_name_full_prefix(self):
        self.assertTrue(server._word_owner_file_matches("~$test.docx", "test.docx"))

    def test_long_name_first_two_chars_dropped(self):
        self.assertTrue(
            server._word_owner_file_matches("~$oposal-Final.docx", "Proposal-Final.docx")
        )

    def test_unrelated_owner_file_does_not_match(self):
        self.assertFalse(server._word_owner_file_matches("~$other-file.docx", "test.docx"))

    def test_non_owner_file_does_not_match(self):
        self.assertFalse(server._word_owner_file_matches("notes.docx", "test.docx"))

    def test_wrong_character_count_dropped_does_not_match(self):
        # Only 0 or exactly 2 dropped characters are valid per the documented
        # rule; a candidate that would require dropping e.g. 1 or 3 must not
        # match even if it happens to share a long suffix.
        self.assertFalse(server._word_owner_file_matches("~$posal-Final.docx", "Proposal-Final.docx"))


class OwnerFileDetectionTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.directory = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_no_owner_file_present(self):
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertEqual(
            result, {"present": False, "path": None, "format": None, "owner_name": None}
        )

    def test_word_owner_file_detected_and_parsed(self):
        owner_file = self.directory / "~$test.docx"
        # Synthetic header: NUL/control padding, then the owner's plain-text
        # display name — the commonly documented layout, since confirmed
        # against a REAL Word-generated owner file in WP-02 review (see
        # server.py's _parse_word_owner_name docstring). This fixture
        # stays synthetic (a real owner file needs a live, concurrent
        # Word session, not reproducible in an offline unit test) but the
        # layout it encodes is no longer just "commonly documented" —
        # it's verified.
        owner_file.write_bytes(b"\x00\x00\x00\x00\x00\x00\x00\x00\x18Michael Sutton\x00\x00")
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertTrue(result["present"])
        self.assertEqual(result["format"], "word")
        self.assertEqual(result["owner_name"], "Michael Sutton")

    def test_libreoffice_lock_file_detected_and_parsed(self):
        lock_file = self.directory / ".~lock.test.docx#"
        lock_file.write_bytes(
            b",Michael Sutton,,msutton-mbp,10.09.2026 14:00:00,file:///Users/msutton/test.docx;"
        )
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertTrue(result["present"])
        self.assertEqual(result["format"], "libreoffice")
        self.assertEqual(result["owner_name"], "Michael Sutton")

    def test_libreoffice_lock_preferred_over_word_owner_file_when_both_present(self):
        # Not expected in practice (the two apps' lock conventions don't
        # normally coexist for the same file), but the lookup order should
        # still be deterministic rather than glob-order-dependent.
        (self.directory / ".~lock.test.docx#").write_bytes(b",Someone,,,")
        (self.directory / "~$test.docx").write_bytes(b"\x00Other Person\x00")
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertEqual(result["format"], "libreoffice")


class SyncQuiesceTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self._old_allowed = os.environ.get(paths._ALLOWED_FILE_ROOTS_ENV)
        os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._tmp.name
        self.target = Path(self._tmp.name) / "doc.docx"
        self.target.write_bytes(b"stub content")

    def tearDown(self):
        if self._old_allowed is None:
            os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        else:
            os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._old_allowed
        self._tmp.cleanup()

    def test_stable_file_reports_quiesced(self):
        sleeps: list[float] = []
        result = server.execute_lock_status(str(self.target), sleep=sleeps.append)
        self.assertTrue(result["sync_quiesced"])
        self.assertEqual(sleeps, [1.5])
        self.assertEqual(result["sync_detail"]["sample_1"], result["sync_detail"]["sample_2"])
        self.assertEqual(result["sync_detail"]["tmp_siblings"], [])

    def test_tmp_sibling_reports_not_quiesced(self):
        (Path(self._tmp.name) / "doc.docx.tmp").write_bytes(b"partial")
        result = server.execute_lock_status(str(self.target), sleep=lambda s: None)
        self.assertFalse(result["sync_quiesced"])
        self.assertEqual(len(result["sync_detail"]["tmp_siblings"]), 1)

    def test_size_change_between_samples_reports_not_quiesced(self):
        calls = {"n": 0}

        def growing_sleep(interval):
            calls["n"] += 1
            self.target.write_bytes(b"stub content, now longer")

        result = server.execute_lock_status(str(self.target), sleep=growing_sleep)
        self.assertFalse(result["sync_quiesced"])
        self.assertEqual(calls["n"], 1)

    def test_owner_file_present_does_not_refuse_lock_status(self):
        # core/document-backend-protocol.md §4: DOCX_LOCKED gates writes
        # only. lock_status must still return normally, reporting the
        # owner file as data.
        (Path(self._tmp.name) / "~$doc.docx").write_bytes(b"\x00Someone\x00")
        result = server.execute_lock_status(str(self.target), sleep=lambda s: None)
        self.assertTrue(result["owner_file"]["present"])


if __name__ == "__main__":
    unittest.main()
