"""Unit tests for src/verified_docx_mcp/server.py.

Covers the two issue #28 WP-02 acceptance items not already covered by
test_render.py / test_paths.py:

  - error mapping: execute_export_pdf() translates render.RenderError codes
    1:1 onto this server's own ErrorCode/VerifyError envelope (exercised,
    like test_render.py's ErrorMappingTests, via a fake `osascript` earlier
    on PATH rather than a real Word instance).
  - close_after wiring (issue #103): execute_export_pdf()'s closed_after /
    close_error / left_open_document result fields and the close_after ->
    close_mode argv pass-through, via a fake `osascript` that simulates a
    successful render (same technique as test_render.py's CloseAfterTests).
  - owner-file parsing: Word's "~$*" suffix-matching rule and LibreOffice's
    ".~lock.<name>#", both via synthetic fixtures (see paths.py / server.py
    docstrings for why real-Word-generated bytes are out of reach here —
    a LEAD: acceptance item).
"""

from __future__ import annotations

import os
import shlex
import shutil
import stat
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))

from verified_docx_mcp import paths, server
from verified_docx_mcp.errors import ErrorCode, VerifyError

FIXTURE_DIR = REPO / "tests" / "fixtures"
# A real, valid .docx with zero headings (confirmed via find_sections_impl)
# -- used wherever a test needs execute_export_pdf's *source* path to
# survive projection.find_sections_impl() (issue #102's section-geometry
# planning runs before render_word() is ever invoked) without pulling in
# any actual section probing. Tests exercising rendering-path behavior
# unrelated to sections (error mapping, close_after) use this rather than
# a fake byte blob, now that execute_export_pdf reads the source .docx
# directly (not just stages it for a mocked Word to "open").
NO_HEADINGS_FIXTURE = FIXTURE_DIR / "frag.docx"


def _write_fake_osascript(bin_dir: Path, stderr_text: str, exit_code: int = 1) -> None:
    script = bin_dir / "osascript"
    script.write_text(
        "#!/bin/sh\n"
        f"echo {stderr_text!r} 1>&2\n"
        f"exit {exit_code}\n",
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


class ExportPdfErrorMappingTests(unittest.TestCase):
    """execute_export_pdf()'s RenderError -> VerifyError translation.

    Guarded on Word's sandbox container directory actually existing —
    render_word() checks that BEFORE ever invoking osascript (same guard
    as test_render.py's ErrorMappingTests)."""

    def setUp(self):
        import verified_docx_mcp.render as render_module

        if not render_module._word_sandbox_root().is_dir():
            self.skipTest(
                "Word's sandbox container directory does not exist on this "
                "machine (Word never launched)."
            )
        self._tmp = tempfile.TemporaryDirectory()
        self._bin_dir = Path(self._tmp.name) / "bin"
        self._bin_dir.mkdir()
        self._old_path = os.environ.get("PATH", "")
        os.environ["PATH"] = f"{self._bin_dir}{os.pathsep}{self._old_path}"

        self._old_allowed = os.environ.get(paths._ALLOWED_FILE_ROOTS_ENV)
        os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._tmp.name

        self._in_path = Path(self._tmp.name) / "test-input.docx"
        # A real, headingless .docx (issue #102: execute_export_pdf now
        # calls projection.find_sections_impl() on the source BEFORE
        # render_word() is invoked, which needs a real OOXML zip --
        # osascript itself still never reads this file's bytes, only
        # Python's own zipfile-based section planning does.
        shutil.copyfile(NO_HEADINGS_FIXTURE, self._in_path)
        self._out_path = Path(self._tmp.name) / "out" / "test-output.pdf"
        self._out_path.parent.mkdir()

    def tearDown(self):
        os.environ["PATH"] = self._old_path
        if self._old_allowed is None:
            os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        else:
            os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._old_allowed
        self._tmp.cleanup()

    def test_automation_not_granted_maps_through(self):
        _write_fake_osascript(
            self._bin_dir,
            "execution error: Not authorized to send Apple events to Microsoft Word. (-1743)",
        )
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), str(self._out_path))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.AUTOMATION_NOT_GRANTED)

    def test_other_failure_maps_to_render_failed(self):
        _write_fake_osascript(self._bin_dir, "Error: Message not understood.")
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), str(self._out_path))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.RENDER_FAILED)
        self.assertIn("Message not understood", str(ctx.exception.envelope.diagnostics))


def _write_fake_osascript_success(bin_dir: Path, stdout_text: str, args_log: Path | None = None) -> None:
    """A fake `osascript` that simulates a SUCCESSFUL render: it writes a
    few placeholder bytes to the staged-output path (the AppleScript
    worker's own outPath, i.e. "item 2 of argv" -> the fake's own $3, since
    $1 is the .applescript file and $2 is the staged input), so
    render_word()'s staged_out.is_file() check passes without a real Word
    instance. The placeholder bytes are not a real PDF, so the pdfinfo/
    regex cross-check in execute_export_pdf() returns (None, None) — the
    tests below only rely on Word's own reported page count ("word"
    source), which does not need a real PDF. Prints stdout_text (the
    "OK <pages> closed=<0|1> <err>" line under test) and exits 0. When
    args_log is given, the fake also writes its own argv (space-joined)
    there, so a test can assert the close_mode argument (AppleScript's
    "item 4 of argv", added for issue #103) took the expected value."""
    lines = ["#!/bin/sh", 'printf "%%PDF-1.4 placeholder" > "$3"']
    if args_log is not None:
        lines.append(f'echo "$@" > {shlex.quote(str(args_log))}')
    lines.append(f"echo {stdout_text!r}")
    lines.append("exit 0")
    script = bin_dir / "osascript"
    script.write_text("\n".join(lines) + "\n", encoding="utf-8")
    script.chmod(script.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


class ExportPdfCloseAfterTests(unittest.TestCase):
    """execute_export_pdf()'s closed_after / close_error / left_open_document
    wiring and the close_after -> close_mode argv pass-through (issue #103).

    Same sandbox-dir guard and fake-osascript setup as
    ExportPdfErrorMappingTests above, reusing test_render.py's
    CloseAfterTests fake-osascript-success shape (a fake that touches/
    writes the staged output so render_word()'s own file-exists check
    passes, then prints the "OK <pages> closed=<0|1> <err>" line)."""

    def setUp(self):
        import verified_docx_mcp.render as render_module

        if not render_module._word_sandbox_root().is_dir():
            self.skipTest(
                "Word's sandbox container directory does not exist on this "
                "machine (Word never launched)."
            )
        self._tmp = tempfile.TemporaryDirectory()
        self._bin_dir = Path(self._tmp.name) / "bin"
        self._bin_dir.mkdir()
        self._old_path = os.environ.get("PATH", "")
        os.environ["PATH"] = f"{self._bin_dir}{os.pathsep}{self._old_path}"

        self._old_allowed = os.environ.get(paths._ALLOWED_FILE_ROOTS_ENV)
        os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._tmp.name

        self._in_path = Path(self._tmp.name) / "test-input.docx"
        # A real, headingless .docx (issue #102: execute_export_pdf now
        # calls projection.find_sections_impl() on the source BEFORE
        # render_word() is invoked, which needs a real OOXML zip --
        # osascript itself still never reads this file's bytes, only
        # Python's own zipfile-based section planning does.
        shutil.copyfile(NO_HEADINGS_FIXTURE, self._in_path)
        self._out_path = Path(self._tmp.name) / "out" / "test-output.pdf"
        self._out_path.parent.mkdir()

    def tearDown(self):
        os.environ["PATH"] = self._old_path
        if self._old_allowed is None:
            os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        else:
            os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._old_allowed
        self._tmp.cleanup()

    def test_closed_after_true(self):
        _write_fake_osascript_success(self._bin_dir, "OK 3 closed=1 ")
        result = server.execute_export_pdf(str(self._in_path), str(self._out_path))
        self.assertTrue(result["closed_after"])
        self.assertIsNone(result["close_error"])
        self.assertIsNone(result["left_open_document"])
        self.assertEqual(result["page_count"], 3)
        self.assertEqual(result["page_count_source"], "word")

    def test_closed_after_false_with_close_error_and_no_exception(self):
        _write_fake_osascript_success(
            self._bin_dir,
            "OK 3 closed=0 -1708 doesn't understand the close message",
        )
        # No exception: a close failure is reported, never fatal.
        result = server.execute_export_pdf(str(self._in_path), str(self._out_path))
        self.assertFalse(result["closed_after"])
        self.assertTrue(result["left_open_document"])
        self.assertIn("-1708", result["close_error"])

    def test_close_after_false_passes_keep_argument(self):
        args_log = Path(self._tmp.name) / "argv.log"
        _write_fake_osascript_success(self._bin_dir, "OK 3 closed=0 ", args_log=args_log)
        result = server.execute_export_pdf(
            str(self._in_path), str(self._out_path), close_after=False
        )
        self.assertFalse(result["closed_after"])
        logged_argv = args_log.read_text().strip().split()
        # AppleScript's own "item 4 of argv" (the close_mode); the fake
        # osascript's positional $1 is the .applescript file itself, so
        # this is logged_argv[-1] (the last of the five shell args).
        self.assertEqual(logged_argv[-1], "keep", logged_argv)


class ExportPdfPathValidationTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self._old_allowed = os.environ.get(paths._ALLOWED_FILE_ROOTS_ENV)
        os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._tmp.name
        self._in_path = Path(self._tmp.name) / "in.docx"
        self._in_path.write_bytes(b"stub")

    def tearDown(self):
        if self._old_allowed is None:
            os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        else:
            os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._old_allowed
        self._tmp.cleanup()

    def test_missing_parent_directory_rejected(self):
        out = Path(self._tmp.name) / "does-not-exist-dir" / "out.pdf"
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), str(out))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.INVALID_INPUT)

    def test_empty_output_path_rejected(self):
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(self._in_path), "")
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.INVALID_INPUT)

    def test_missing_source_rejected(self):
        out = Path(self._tmp.name) / "out.pdf"
        with self.assertRaises(VerifyError) as ctx:
            server.execute_export_pdf(str(Path(self._tmp.name) / "nope.docx"), str(out))
        self.assertEqual(ctx.exception.envelope.error_code, ErrorCode.INVALID_INPUT)

    def test_output_path_under_scratch_root_accepted(self):
        # issue #101: with VERIFIED_DOCX_MCP_ALLOWED_FILE_ROOTS unset, an
        # output_path under the (patched) Claude Code scratch root resolves
        # rather than being rejected as outside the allowed roots.
        os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        with tempfile.TemporaryDirectory() as scratch_dir:
            scratch_root = Path(scratch_dir)
            out = scratch_root / "out.pdf"
            with mock.patch.object(paths, "_claude_code_scratch_root", return_value=scratch_root):
                resolved = server._resolve_export_output_path(str(out))
            self.assertEqual(resolved, out.resolve())


class WordOwnerFileMatchTests(unittest.TestCase):
    """core/document-backend-protocol.md §9's shared-filename-suffix rule."""

    def test_short_name_full_prefix(self):
        self.assertTrue(server._word_owner_file_matches("~$test.docx", "test.docx"))

    def test_long_name_first_two_chars_dropped(self):
        self.assertTrue(
            server._word_owner_file_matches("~$oposal-Final.docx", "Proposal-Final.docx")
        )

    def test_unrelated_owner_file_does_not_match(self):
        self.assertFalse(server._word_owner_file_matches("~$other-file.docx", "test.docx"))

    def test_non_owner_file_does_not_match(self):
        self.assertFalse(server._word_owner_file_matches("notes.docx", "test.docx"))

    def test_wrong_character_count_dropped_does_not_match(self):
        # Only 0 or exactly 2 dropped characters are valid per the documented
        # rule; a candidate that would require dropping e.g. 1 or 3 must not
        # match even if it happens to share a long suffix.
        self.assertFalse(server._word_owner_file_matches("~$posal-Final.docx", "Proposal-Final.docx"))


class OwnerFileDetectionTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.directory = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_no_owner_file_present(self):
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertEqual(
            result, {"present": False, "path": None, "format": None, "owner_name": None}
        )

    def test_word_owner_file_detected_and_parsed(self):
        owner_file = self.directory / "~$test.docx"
        # Synthetic header: NUL/control padding, then the owner's plain-text
        # display name — the commonly documented layout, since confirmed
        # against a REAL Word-generated owner file in WP-02 review (see
        # server.py's _parse_word_owner_name docstring). This fixture
        # stays synthetic (a real owner file needs a live, concurrent
        # Word session, not reproducible in an offline unit test) but the
        # layout it encodes is no longer just "commonly documented" —
        # it's verified.
        owner_file.write_bytes(b"\x00\x00\x00\x00\x00\x00\x00\x00\x18Michael Sutton\x00\x00")
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertTrue(result["present"])
        self.assertEqual(result["format"], "word")
        self.assertEqual(result["owner_name"], "Michael Sutton")

    def test_libreoffice_lock_file_detected_and_parsed(self):
        lock_file = self.directory / ".~lock.test.docx#"
        lock_file.write_bytes(
            b",Michael Sutton,,msutton-mbp,10.09.2026 14:00:00,file:///Users/msutton/test.docx;"
        )
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertTrue(result["present"])
        self.assertEqual(result["format"], "libreoffice")
        self.assertEqual(result["owner_name"], "Michael Sutton")

    def test_libreoffice_lock_preferred_over_word_owner_file_when_both_present(self):
        # Not expected in practice (the two apps' lock conventions don't
        # normally coexist for the same file), but the lookup order should
        # still be deterministic rather than glob-order-dependent.
        (self.directory / ".~lock.test.docx#").write_bytes(b",Someone,,,")
        (self.directory / "~$test.docx").write_bytes(b"\x00Other Person\x00")
        result = server._find_owner_file(self.directory, "test.docx")
        self.assertEqual(result["format"], "libreoffice")


class SyncQuiesceTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self._old_allowed = os.environ.get(paths._ALLOWED_FILE_ROOTS_ENV)
        os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._tmp.name
        self.target = Path(self._tmp.name) / "doc.docx"
        self.target.write_bytes(b"stub content")

    def tearDown(self):
        if self._old_allowed is None:
            os.environ.pop(paths._ALLOWED_FILE_ROOTS_ENV, None)
        else:
            os.environ[paths._ALLOWED_FILE_ROOTS_ENV] = self._old_allowed
        self._tmp.cleanup()

    def test_stable_file_reports_quiesced(self):
        sleeps: list[float] = []
        result = server.execute_lock_status(str(self.target), sleep=sleeps.append)
        self.assertTrue(result["sync_quiesced"])
        self.assertEqual(sleeps, [1.5])
        self.assertEqual(result["sync_detail"]["sample_1"], result["sync_detail"]["sample_2"])
        self.assertEqual(result["sync_detail"]["tmp_siblings"], [])

    def test_tmp_sibling_reports_not_quiesced(self):
        (Path(self._tmp.name) / "doc.docx.tmp").write_bytes(b"partial")
        result = server.execute_lock_status(str(self.target), sleep=lambda s: None)
        self.assertFalse(result["sync_quiesced"])
        self.assertEqual(len(result["sync_detail"]["tmp_siblings"]), 1)

    def test_size_change_between_samples_reports_not_quiesced(self):
        calls = {"n": 0}

        def growing_sleep(interval):
            calls["n"] += 1
            self.target.write_bytes(b"stub content, now longer")

        result = server.execute_lock_status(str(self.target), sleep=growing_sleep)
        self.assertFalse(result["sync_quiesced"])
        self.assertEqual(calls["n"], 1)

    def test_owner_file_present_does_not_refuse_lock_status(self):
        # core/document-backend-protocol.md §4: DOCX_LOCKED gates writes
        # only. lock_status must still return normally, reporting the
        # owner file as data.
        (Path(self._tmp.name) / "~$doc.docx").write_bytes(b"\x00Someone\x00")
        result = server.execute_lock_status(str(self.target), sleep=lambda s: None)
        self.assertTrue(result["owner_file"]["present"])


if __name__ == "__main__":
    unittest.main()
